# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spot_info',
        ),
        migrations.DeleteModel(
            name='spot_status',
        ),
    ]
