# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_log',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.spot_data'),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
