# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170515_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_log',
            name='total_paid',
            field=models.FloatField(default=0, verbose_name=b'Total charge'),
        ),
    ]
