# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_payment_method'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_methods',
            field=models.ManyToManyField(to='monitor.payment_method'),
        ),
    ]
