# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spot_data',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=b'UUID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Active')),
                ('section', models.CharField(max_length=20, verbose_name=b'Section')),
                ('number', models.IntegerField(verbose_name=b'Spot Number')),
                ('description', models.CharField(max_length=50, verbose_name=b'Description')),
                ('gpslat', models.FloatField(null=True, verbose_name=b'Latitude')),
                ('gpslon', models.FloatField(null=True, verbose_name=b'Longitude')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name=b'Last Update')),
                ('occ_status', models.SmallIntegerField(default=0, verbose_name=b'Occupied Status')),
                ('occ_since', models.DateTimeField(verbose_name=b'Occupied Since')),
                ('occ_license', models.CharField(max_length=20, verbose_name=b'Occupant License')),
            ],
        ),
        migrations.CreateModel(
            name='spot_sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Section')),
            ],
        ),
        migrations.CreateModel(
            name='spot_structs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Structure')),
            ],
        ),
    ]
