# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spot_data',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=b'UUID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Active')),
                ('section', models.CharField(max_length=20, verbose_name=b'Section')),
                ('number', models.IntegerField(verbose_name=b'Spot Number')),
                ('description', models.CharField(max_length=50, verbose_name=b'Description')),
                ('gpslat', models.FloatField(null=True, verbose_name=b'Latitude')),
                ('gpslon', models.FloatField(null=True, verbose_name=b'Longitude')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name=b'Last Update')),
                ('occ_status', models.SmallIntegerField(default=0, verbose_name=b'Occupied Status')),
                ('occ_since', models.DateTimeField(verbose_name=b'Occupied Since')),
                ('occ_license', models.CharField(max_length=20, verbose_name=b'Occupant License')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot_info',
            name='status',
        ),
        migrations.RemoveField(
            model_name='spot_status',
            name='info',
        ),
        migrations.DeleteModel(
            name='spot_info',
        ),
        migrations.DeleteModel(
            name='spot_status',
        ),
    ]
