# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20170307_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='spot_sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Section')),
            ],
        ),
        migrations.CreateModel(
            name='spot_structs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Structure')),
            ],
        ),
    ]
