# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_spot_data_occupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot_data',
            name='section',
        ),
    ]
