# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_remove_spot_data_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot_data',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='sensor.spot_sections'),
        ),
        migrations.AddField(
            model_name='spot_data',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='sensor.spot_structs'),
        ),
    ]
