# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20170504_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spot_structs',
            new_name='structures',
        ),
    ]
