# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20170504_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.structures'),
        ),
    ]
