# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_sections_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot_data',
            name='occupant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot_data',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sections'),
        ),
        migrations.AlterField(
            model_name='spot_data',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.structures'),
        ),
    ]
