# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_auto_20170505_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot_data',
            name='structure',
        ),
    ]
