# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_remove_spot_data_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='rate',
            field=models.FloatField(null=True, verbose_name=b'Rate'),
        ),
    ]
