# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_auto_20170510_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot_data',
            name='rate',
            field=models.IntegerField(default=0, verbose_name=b'OLD RATE'),
        ),
    ]
