# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0013_spot_data_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot_data',
            name='rate',
            field=models.FloatField(default=0, verbose_name=b'OLD RATE'),
        ),
    ]
