# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import sensor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0015_auto_20170515_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='rates',
            field=models.TextField(default=sensor.models.rates_default, verbose_name=b'Rates Array'),
        ),
    ]
